#import "../departmentFragment.gql"
mutation AddDepartment($teamLead:ID!, $name:String!, $lastMilestone:String!, $status:Status!){
    addDepartment(department:{teamLead:$teamLead, name:$name, lastMilestone:$lastMilestone,status:$status}){
        ...departmentInfo
    }
}