#import "../departmentFragment.gql"
mutation UpdateDepartment($id:ID!,$name:String, $lastMilestone:String, $status:Status){
    updateDepartment(_id:$id, department:{name:$name, lastMilestone:$lastMilestone,status:$status}){
        ...departmentInfo
    }
}