#import "./fragments.gql"
mutation AddDepartment($teamLead:ID!, $name:String, $lastMilestone:String, $status:Status){
    addDepartment(department:{teamLead:$teamLead, name:$name, lastMilestone:$lastMilestone,status:$status}){
        ...departmentInfo
    }
}

mutation UpdateDepartment($id:ID!, $teamLead:ID, $name:String, $lastMilestone:String, $status:Status){
    updateDepartment(_id:$id, department:{teamLead:$teamLead, name:$name, lastMilestone:$lastMilestone,status:$status}){
        ...departmentInfo
    }
}

mutation ChangeTeamLead($id:ID!, $teamLead:ID){
    changeTeamLead(_id:$id, department:{teamLead:$teamLead}){
        ...departmentInfo
    }
}

mutation DeleteDepartment($id:ID!){
    deleteDepartment(_id:$id){
        ...departmentInfo
    }
}