fragment memberInfo on Member{
    _id,
    name,
    email,
    phone,
}

fragment departmentInfo on Department{
    _id,
    teamLead{
            id
        name
        email
        phone
    },
    name,
    lastMilestone,
    status,
}