#import "./fragments.gql"
mutation AddMember($name:String!,$email:String!,$phone:String!){
    addMember(member:{name:$name,email:$email,phone:$phone}){
        ...memberInfo
    }
}

mutation UpdateMember($id:ID!,$name:String,$email:String,$phone:String){
    updateMember(_id:$id,member:{name:$name,email:$email,phone:$phone}){
        ...memberInfo
    }
}

mutation DeleteMember($id:ID!){
    updateMember(_id:$id){
        ...memberInfo
    }
}

