type Member{
	_id:ID!,
	name: String,
	email: String,
	phone: String,
}

type Update{
    message: String,
    time: String,
}

type Query {
	members:[Member],
	member(_id:ID!): Member,
}

type Mutation {
	addMember(member:CreateMemberInput):Member!,
	updateMember(_id:ID!,member:UpdateMemberInput):Member!,
	deleteMember(_id:ID!):Member!,
}

input CreateMemberInput {
    name: String!,
	email: String!,
	phone: String!,
}
  
input UpdateMemberInput {
    name: String,
	email: String,
	phone: String,
} 